Repository cristiano-nicolau/SensorSafe, pull requests merged in 2023-12, with the labels that each got.

#15 New/list sensors and devices for rooms
  README.md
  project/sensorsafe/src/Components/Rooms.js
Labels: feature

#16 Fix/devices and sensors problem
  project/sensorsafe/src/Components/Devices.js
Labels: bug

#20 commit
  API/src/main/java/com/SensorSafe/API/controller/DeviceApiController.java
  API/src/main/java/com/SensorSafe/API/controller/RoomsApiController.java
  API/src/main/java/com/SensorSafe/API/services/AvailableDeviceService.java
  API/src/main/java/com/SensorSafe/API/services/DeviceService.java
  project/sensorsafe/src/Components/CardDevices.js
  project/sensorsafe/src/Components/Rooms.js
  project/sensorsafe/src/Css/Cards.css
  project/sensorsafe/src/Css/Rooms.css
Labels: bug, feature

#22 fixed
  API/src/main/java/com/SensorSafe/API/controller/MiddlewareApiController.java
  API/src/main/java/com/SensorSafe/API/model/report/Report.java
  API/src/main/java/com/SensorSafe/API/model/report/ReportSensorItem.java
  API/src/main/java/com/SensorSafe/API/repository/SensorReportRepository.java
  API/src/main/java/com/SensorSafe/API/services/ReportSensorService.java
Labels: bug

#23 esta feito
  API/src/main/java/com/SensorSafe/API/controller/MiddlewareApiController.java
  API/src/main/java/com/SensorSafe/API/midleware/MiddlewareHandler.java
Labels: feature

#24 New/room create fix
  project/sensorsafe/src/Components/CreateRoom.js
  project/sensorsafe/src/Components/Devices.js
  project/sensorsafe/src/Components/Rooms.js
  project/sensorsafe/src/Css/CreateRoom.css
Labels: bug

#26 reports start
  API/src/main/java/com/SensorSafe/API/controller/RoomsApiController.java
  project/sensorsafe/src/Components/Dashboard.js
  project/sensorsafe/src/Components/DeviceInfo.js
  project/sensorsafe/src/Components/SensorsSelector.js
  project/sensorsafe/src/Css/Dashboard.css
  project/sensorsafe/src/Css/RoomSelector.css
Labels: feature

#28 Fix/report generation
  API/src/main/java/com/SensorSafe/API/controller/ReportsApiController.java
  API/src/main/java/com/SensorSafe/API/services/ReportService.java
  project/docker-compose.yml
  project/sensorsafe/src/Components/ReportsSection.js
  report_generation/Dockerfile
  report_generation/apiHandler.py
  report_generation/generate_report_maintenance.py
  report_generation/generate_report_stats.py
  report_generation/report.pdf
  report_generation/requirements.txt
  report_generation/run.sh
  report_generation/server.py
Labels: bug
